services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db with_payload=True

  valkey:
    image: valkey/valkey:latest
    ports:
      - 6379:6379
    volumes:
      - valkey_data:/usr/local/etc/valkey

  neo4j:
    image: neo4j:5
    restart: always
    ports:
      - "7474:7474" # Neo4j browser
      - "7687:7687" # Bolt protocol
    environment:
      NEO4J_AUTH: neo4j/password123
    volumes:
      - neo4j_data:/data

  qdrant:
    image: qdrant/qdrant
    restart: always
    ports:
      - "6333:6333" # HTTP API
      - "6334:6334" # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage

  # worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   # command:
  #   #   ["rq", "worker", "--with-scheduler", "--url", "redis://valkey:6379"]
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - qdrant
  #     - neo4j
  #     - valkey
  #     - mongo

volumes:
  mongodb_data:
  valkey_data:
  neo4j_data:
  qdrant_data:
